Updated README.md file
dailydotdev/docs pull request #118
Opened 2022-09-13 02:27 UTC by SaptarshiSarkar12

Updated the `thanks to all contributors` section by adding avatars of the contributors.

2022-09-13 02:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dailydotdev/docs?pullRequest=118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dailydotdev/docs?pullRequest=118) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dailydotdev/docs?pullRequest=118) it.</sub>

2022-09-15 10:12 UTC, SaptarshiSarkar12 commented
@FrancescoXX Please review this PR

2022-09-16 10:29 UTC, GrahamTheDev requested changes
Thanks for this, great suggestion, just that one fix and we can merge!

2022-09-16 10:29 UTC, GrahamTheDev commented on README.md
> +   <img src = "https://contrib.rocks/image?repo=dailydotdev/docs"/>
Could you add an alt tag to the image and then we can merge this PR (otherwise people using a screen reader will reach a link that will have no programmatically determinable text).

I would suggest "Contributors to daily.dev docs" as a suitable alt tag.

2022-09-16 13:06 UTC, SaptarshiSarkar12 commented on README.md
> +   <img src = "https://contrib.rocks/image?repo=dailydotdev/docs"/>
Sure @GrahamTheDev

2022-09-16 13:07 UTC, SaptarshiSarkar12 commented on README.md
> +   <img src = "https://contrib.rocks/image?repo=dailydotdev/docs"/>
Done @GrahamTheDev . Please re-review this PR.

2022-10-25 13:23 UTC, SaptarshiSarkar12 commented
@GrahamTheDev Please re-review this PR.

2022-10-28 12:05 UTC, merged

2022-10-28 14:26 UTC, SaptarshiSarkar12 commented
Thanks for reviewing this PR @FrancescoXX 😄.