added command for update npm
dailydotdev/docs pull request #146
Opened 2022-10-02 06:35 UTC by Dnyaneshvn

2022-10-02 21:27 UTC, thinkverse commented
`npm install latest-version` does not update your NPM to the latest version.

All that command does is installs the package named [latest-version](https://www.npmjs.com/package/latest-version).

To update to the latest version of NPM you have to install it globally.

```bash
npm install --global npm@latest
```

2022-10-03 03:09 UTC, Dnyaneshvn commented
ok

2022-10-27 11:00 UTC, NehaGupta1409 reviewed
please revert anything else but the npm install command

2022-10-28 12:24 UTC, GrahamTheDev requested changes

2022-10-28 12:24 UTC, GrahamTheDev commented on README.md
> +$ npm install latest-version
Could you move this out of "Run the local dev environment:" section and put it in it "Install the dependencies:" or in its own section.

At the moment it might make people think they need to run it every time the start the project.

2022-10-28 14:05 UTC, Dnyaneshvn commented on README.md
> +$ npm install latest-version
okay, I will do

2023-06-22 04:03 UTC, FrancescoXX commented
this  command is not needed at the moment

2023-06-22 04:03 UTC, closed without merging