Updated Preferences section
dailydotdev/docs pull request #153
Opened 2022-10-04 11:44 UTC by thisiskaransgit

Fixes issue #149 
Added sub-section for `show weekly goal widget` and `enable companion` switch 
![Screenshot from 2022-10-04 17-10-16](https://user-images.githubusercontent.com/92504666/193811376-01012e5a-2c14-4d71-b400-3d3c74eb8f0e.png)

2022-10-04 11:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dailydotdev/docs?pullRequest=153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dailydotdev/docs?pullRequest=153) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dailydotdev/docs?pullRequest=153) it.</sub>

2022-10-04 14:14 UTC, vikasganiga05 approved these changes
It looks good to me. Thanks for the contribution :tada:

2022-10-07 14:53 UTC, GrahamTheDev requested changes
Thanks for the PR, if you can make that one quick change that would be great.

2022-10-07 14:53 UTC, GrahamTheDev commented on docs/customize-your-feed/preferences.md
> +Turning this toggle switch `on` will activate the companion widget. To know more about it click [here](https://docs.daily.dev/docs/key-features/the-companion)
Hey, quick fix here, could you just change it so that it says "activate [the companion widget](link)" and then remove the last sentence. 

After that I will merge 💪

2022-10-07 17:22 UTC, thisiskaransgit commented on docs/customize-your-feed/preferences.md
> +Turning this toggle switch `on` will activate the companion widget. To know more about it click [here](https://docs.daily.dev/docs/key-features/the-companion)
Done!

2022-10-28 12:09 UTC, merged