community picks new page
dailydotdev/docs pull request #84
Opened 2022-07-13 13:40 UTC by GrahamTheDev

2022-07-13 13:59 UTC, idoshamun commented on docs/key-features/community-picks.md
> +## Submitting a Community Pick
It think it's more aligned with our terminology

```suggestion
## Scouting a Community Pick
```

2022-07-13 13:59 UTC, idoshamun commented on docs/key-features/community-picks.md
> +On the menu on the left you will see a new section "Contribute" containing a button "Submit article".
`new` is a relative term that doesn't hold in the test of time. I recommend removing it

2022-07-13 14:01 UTC, idoshamun commented on docs/key-features/community-picks.md
> +![](https://daily-now-res.cloudinary.com/image/upload/v1657719512/cp-4-not-enough-permissions_zadogk.jpg)
The image looks buggy because it says 4/3

2022-07-13 14:06 UTC, idoshamun commented on docs/key-features/community-picks.md
> +## What do we want to see?
I'm not sure people will read this far and I want to make sure they know our guidelines before they understand how to submit.

An important point that is missing: "don't submit your own articles".

2022-07-13 14:07 UTC, idoshamun commented on docs/key-features/community-picks.md
> +You gain reputation on any link you submit when it receives an upvote, as well as the post author if they have a profile on daily.dev.
There's a nuance to this. The upvoter needs to have a certain amount of reputation as well.
It reminds me that we need to update the reputation page as well

2022-07-13 14:08 UTC, idoshamun requested changes
Overall it looks fantastic! I found some missing pieces that I'd love to have

2022-07-14 08:24 UTC, GrahamTheDev commented on docs/key-features/community-picks.md
> +## Submitting a Community Pick
Suggest ## Submitting / Scouting a Community Pick as "Scouting" without explanation might not be clear as an action.

2022-07-14 08:24 UTC, GrahamTheDev commented on docs/key-features/community-picks.md
> +On the menu on the left you will see a new section "Contribute" containing a button "Submit article".
Agreed!

2022-07-14 08:25 UTC, GrahamTheDev commented on docs/key-features/community-picks.md
> +![](https://daily-now-res.cloudinary.com/image/upload/v1657719512/cp-4-not-enough-permissions_zadogk.jpg)
Ah I will fix that, I even noticed it when Chris shared it and then didn't fix, I will fix this after launch

2022-07-14 09:09 UTC, GrahamTheDev commented on docs/key-features/community-picks.md
> +## What do we want to see?
I have added a section to the info part to cover this

2022-07-14 09:11 UTC, merged